#include <stdio.h>
#include <time.h>
#include <stdlib.h>
#include "galois.h"
#include "jerasure.h"
#include "cauchy.h"

//check the feasbility of full rank decompostion in the galois field
//matrix A=BC, A is generated by Jeasure library
//B and C is calculated by the fundamental algorithm for matrics and full rank decomposition method 
// m*k=(m*m) * (m*k)

int k, m, w; //data blocks, parity blocks and parameter of galois field

void matrix_row_transformation(int *matrix, int row1, int row2)//row1 wil be transformed through row2, the first row number begin with one
{
	int i;
	int temp;
	int benchmark_row1,benchmark_row2;
	for(i=0;i<k;i++){
		if( (matrix[(row1-1)*k+i] != 0) && (matrix[(row2-1)*k+i] != 0) ){//search the first non-zero number
			benchmark_row1 = matrix[(row1-1)*k+i];
			benchmark_row2 = matrix[(row2-1)*k+i];	
			break;
		}
	}
	for(;i<k;i++){
		matrix[(row1-1)*k+i] = galois_single_multiply(matrix[(row1-1)*k+i], benchmark_row2, w);
		matrix[(row2-1)*k+i] = galois_single_multiply(matrix[(row2-1)*k+i], benchmark_row1, w);
		matrix[(row1-1)*k+i] = matrix[(row1-1)*k+i] ^ matrix[(row2-1)*k+i];
		matrix[(row2-1)*k+i] = galois_single_divide(matrix[(row2-1)*k+i], benchmark_row1, w);
		matrix[(row1-1)*k+i] = galois_single_divide(matrix[(row1-1)*k+i], benchmark_row2, w);
		//Based on ordinary algorithms
		//matrix[(row1-1)*k+i] *= benchmark_row2;
		//matrix[(row2-1)*k+i] *= benchmark_row1;
		//matrix[(row1-1)*k+i] -= matrix[(row2-1)*k+i]; 
		//matrix[(row2-1)*k+i] /= benchmark_row1;
	}
	jerasure_print_matrix(matrix, m, k, w);
	printf("\n");
}

int matrix_multiplication(int *matrix_b, int *matrix_c, int row, int col)//calcualte the matrix multiplicatioon, row and col begin with one
{
	int i,j,index;
	int temp;
	int sum=0;
	i=(row-1)*m;
	j=col-1;
	for(index=0;index<m;index++){//calculate the sum of row multiple col
		temp = galois_single_multiply(matrix_b[i], matrix_c[j], w);
		sum = sum ^ temp;
		i++;
		j+=k;
	}
	return sum;
}

void calculate_matrix_B(int *matrix_a, int *matrix_b)//matrix B is the submatrix of A
{
	int i,j;
	for(i=1,j=1;i<=k*m;i++,j++){
		matrix_b[j-1] = matrix_a[i-1];
		if((i-m)%k == 0){//the sequence is m, m+k, m+2k......
			i += k-m;
		}
	}
}

void matrix_C_row_transformation(int *matrix_c)//transform matrix C to row simplest through elementary row transformation
{
	int i,j;
	int benchmark;
	printf("the process of the transformation:\n");
	for(i=1;i<m;i++){
		for(j=i+1;j<=m;j++){
			matrix_row_transformation(matrix_c, j, i);
		}
	}
	for(i=1;i<m;i++){
		for(j=i+1;j<=m;j++){
			matrix_row_transformation(matrix_c, i, j);
		}
	}
	for(i=0;i<m;i++){
		for(j=0;j<k;j++){
			if(matrix_c[i*k+j]!=0){
				benchmark = matrix_c[i*k+j];
				break;
			}
		}
		for(j=0;j<k;j++){
			matrix_c[i*k+j] = galois_single_divide(matrix_c[i*k+j],benchmark,w);
		}
	}
}

int check_correctness(int *matrix_a, int *matrix_bc)//check if A equal to B multiple C
{
	int i;
	int judgeflag=1;
	for(i=0;i<m*k;i++){
		if(matrix_a[i] != matrix_bc[i]){
			judgeflag=0;
			printf("%d",judgeflag);
		}
	}
	return judgeflag;
}

int main()
{
	int i,j;
	int index=0;
	int flag;
	printf("Input the parameters k,m,w of matrix A separated by space that you wanna check it decomposition in galois field\n");
	scanf("%d %d %d", &k, &m, &w);
	int *matrix_a = (int *)malloc(m*k*sizeof(int));
	int *matrix_b = (int *)malloc(m*m*sizeof(int));
	int *matrix_c = (int *)malloc(m*k*sizeof(int));
	int *matrix_bc = (int *)malloc(m*k*sizeof(int));
	char *c = (char *)malloc(w);
	
	matrix_a = cauchy_original_coding_matrix(k, m, w);
	printf("matrix A:\n");
	jerasure_print_matrix(matrix_a, m, k, w);
	calculate_matrix_B(matrix_a, matrix_b);
	printf("matrix B:\n");
	jerasure_print_matrix(matrix_b, m, m, w);
	matrix_c = cauchy_original_coding_matrix(k, m, w);
	matrix_C_row_transformation(matrix_c);
	printf("matrix C:\n");
	jerasure_print_matrix(matrix_c, m, k, w);

	for(i=1;i<=m;i++){
		for(j=1;j<=k;j++){
			matrix_bc[index] = matrix_multiplication(matrix_b, matrix_c, i, j);
			index++;
		}
	}
	printf("matrix B multiple matrix C:\n");
	jerasure_print_matrix(matrix_bc, m, k ,w);
	flag = check_correctness(matrix_a, matrix_bc);

	if(flag == 1){
		printf("True\n");
	}
	else{
		printf("False\n");
	}

	printf("Time used=%.5f\n",(double)clock()/CLOCKS_PER_SEC);
	return 0;
}